#!/bin/sh
#
# SccsId = @(#)rmsdflock 1.3 11/18/92 Delft University of Technology
#
if [ "`echo seadif/*.sdk`" = "seadif/*.sdk" ] ; then
   echo "There are no lockfiles seadif/*.sdk ..."
else
   echo Removing lockfiles seadif/*.sdk ...
   rm -f seadif/*.sdk
fi
