.TH _GLOBAL_ROUTING 3 "28 Sep 2000" "madonna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_GLOBAL_ROUTING \- 
.SH SYNOPSIS
.br
.PP
\fC#include <routing.h>\fR
.PP
.SS Public Attributes

.in +1c
.ti -1c
.RI "\fBROUTING_INFO\fR** \fBsmall_channels\fR"
.br
.ti -1c
.RI "\fBROUTING_CHANNEL\fR* \fBhorizontal_channels\fR"
.br
.ti -1c
.RI "\fBROUTING_CHANNEL\fR* \fBvertical_channels\fR"
.br
.in -1c
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS \fBROUTING_CHANNEL\fR * _GLOBAL_ROUTING::horizontal_channels
.PP
Definition at line 41 of file routing.h.
.SS \fBROUTING_INFO\fR ** _GLOBAL_ROUTING::small_channels
.PP
Definition at line 34 of file routing.h.
.SS \fBROUTING_CHANNEL\fR * _GLOBAL_ROUTING::vertical_channels
.PP
Definition at line 42 of file routing.h.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for madonna from the source code.