.TH _IMAGEDESC 3 "28 Sep 2000" "madonna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_IMAGEDESC \- 
.SH SYNOPSIS
.br
.PP
\fC#include <image.h>\fR
.PP
.SS Public Attributes

.in +1c
.ti -1c
.RI "int \fBsize\fR [2]"
.br
.ti -1c
.RI "int \fBoverlap\fR [2]"
.br
.ti -1c
.RI "int** \fBstamp\fR"
.br
.ti -1c
.RI "int \fBnumsector\fR"
.br
.ti -1c
.RI "\fBSECTORLISTPTR\fR \fBsectorlist\fR"
.br
.ti -1c
.RI "int \fBnumaxis\fR"
.br
.ti -1c
.RI "\fBMIRRORPTR\fR \fBmirroraxis\fR"
.br
.ti -1c
.RI "int \fBnumlayers\fR"
.br
.ti -1c
.RI "int* \fBrouteorient\fR"
.br
.ti -1c
.RI "int* \fBestransp\fR"
.br
.ti -1c
.RI "\fBPOWERLINEPTR\fR \fBpowerlines\fR"
.br
.in -1c
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS int * _IMAGEDESC::estransp
.PP
Definition at line 66 of file image.h.
.SS \fBMIRRORPTR\fR _IMAGEDESC::mirroraxis
.PP
Definition at line 63 of file image.h.
.SS int _IMAGEDESC::numaxis
.PP
Definition at line 62 of file image.h.
.SS int _IMAGEDESC::numlayers
.PP
Definition at line 64 of file image.h.
.SS int _IMAGEDESC::numsector
.PP
Definition at line 60 of file image.h.
.SS int _IMAGEDESC::overlap[2]
.PP
Definition at line 58 of file image.h.
.SS \fBPOWERLINEPTR\fR _IMAGEDESC::powerlines
.PP
Definition at line 67 of file image.h.
.SS int * _IMAGEDESC::routeorient
.PP
Definition at line 65 of file image.h.
.SS \fBSECTORLISTPTR\fR _IMAGEDESC::sectorlist
.PP
Definition at line 61 of file image.h.
.SS int _IMAGEDESC::size[2]
.PP
Definition at line 57 of file image.h.
.SS int ** _IMAGEDESC::stamp
.PP
Definition at line 59 of file image.h.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for madonna from the source code.