.TH _MIR 3 "28 Sep 2000" "madonna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_MIR \- 
.SH SYNOPSIS
.br
.PP
\fC#include <plaza.h>\fR
.PP
.SS Public Attributes

.in +1c
.ti -1c
.RI "int \fBarea\fR"
.br
.ti -1c
.RI "int \fBmorearea\fR"
.br
.ti -1c
.RI "short \fBmtx\fR [6]"
.br
.in -1c
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS int _MIR::area
.PP
Definition at line 12 of file plaza.h.
.SS int _MIR::morearea
.PP
Definition at line 13 of file plaza.h.
.SS short _MIR::mtx[6]
.PP
Definition at line 14 of file plaza.h.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for madonna from the source code.