.TH _MIRROR 3 "28 Sep 2000" "madonna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_MIRROR \- 
.SH SYNOPSIS
.br
.PP
\fC#include <image.h>\fR
.PP
.SS Public Attributes

.in +1c
.ti -1c
.RI "int \fBaxisid\fR"
.br
.ti -1c
.RI "int \fBlogaxisid\fR"
.br
.ti -1c
.RI "int \fBaxis\fR [4]"
.br
.ti -1c
.RI "\fBEQUIVLISTPTR\fR \fBequivalence\fR"
.br
.ti -1c
.RI "short \fBmtx\fR [6]"
.br
.ti -1c
.RI "int \fBdelta\fR [2]"
.br
.ti -1c
.RI "struct _MIRROR* \fBnext\fR"
.br
.in -1c
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS int _MIRROR::axis[4]
.PP
Definition at line 26 of file image.h.
.SS int _MIRROR::axisid
.PP
Definition at line 25 of file image.h.
.SS int _MIRROR::delta[2]
.PP
Definition at line 29 of file image.h.
.SS \fBEQUIVLISTPTR\fR _MIRROR::equivalence
.PP
Definition at line 27 of file image.h.
.SS int _MIRROR::logaxisid
.PP
Definition at line 25 of file image.h.
.SS short _MIRROR::mtx[6]
.PP
Definition at line 28 of file image.h.
.SS struct _MIRROR * _MIRROR::next
.PP
Definition at line 30 of file image.h.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for madonna from the source code.