.TH _NETSTATE 3 "28 Sep 2000" "madonna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_NETSTATE \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cost.h>\fR
.PP
.SS Public Attributes

.in +1c
.ti -1c
.RI "int* \fBdist\fR"
.br
.ti -1c
.RI "int \fBnx\fR"
.br
.ti -1c
.RI "int \fBny\fR"
.br
.ti -1c
.RI "int \fBcost\fR"
.br
.ti -1c
.RI "int \fBdeviation\fR"
.br
.ti -1c
.RI "int* \fBclm\fR [3]"
.br
.ti -1c
.RI "int* \fBrow\fR [3]"
.br
.ti -1c
.RI "int \fBxl\fR"
.br
.ti -1c
.RI "int \fBxr\fR"
.br
.ti -1c
.RI "int \fByb\fR"
.br
.ti -1c
.RI "int \fByt\fR"
.br
.ti -1c
.RI "int \fBnumparts\fR"
.br
.ti -1c
.RI "int \fBnetid\fR"
.br
.in -1c
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS int * _NETSTATE::clm[3]
.PP
Definition at line 14 of file cost.h.
.SS int _NETSTATE::cost
.PP
Definition at line 12 of file cost.h.
.SS int _NETSTATE::deviation
.PP
Definition at line 13 of file cost.h.
.SS int * _NETSTATE::dist
.PP
Definition at line 9 of file cost.h.
.SS int _NETSTATE::netid
.PP
Definition at line 18 of file cost.h.
.SS int _NETSTATE::numparts
.PP
Definition at line 17 of file cost.h.
.SS int _NETSTATE::nx
.PP
Definition at line 10 of file cost.h.
.SS int _NETSTATE::ny
.PP
Definition at line 10 of file cost.h.
.SS int * _NETSTATE::row[3]
.PP
Definition at line 15 of file cost.h.
.SS int _NETSTATE::xl
.PP
Definition at line 16 of file cost.h.
.SS int _NETSTATE::xr
.PP
Definition at line 16 of file cost.h.
.SS int _NETSTATE::yb
.PP
Definition at line 16 of file cost.h.
.SS int _NETSTATE::yt
.PP
Definition at line 16 of file cost.h.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for madonna from the source code.