.TH _NETCOSTINFO 3 "28 Sep 2000" "madonna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_NETCOSTINFO \- 
.SH SYNOPSIS
.br
.PP
\fC#include <genpart.h>\fR
.PP
.SS Public Attributes

.in +1c
.ti -1c
.RI "int \fBncells\fR"
.br
.ti -1c
.RI "int \fBnumparts\fR"
.br
.ti -1c
.RI "int \fBrow\fR"
.br
.ti -1c
.RI "int \fBclm\fR"
.br
.ti -1c
.RI "\fBCFUNC\fR \fBcostfunction\fR [2]"
.br
.in -1c
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS int _NETCOSTINFO::clm
.PP
Definition at line 97 of file genpart.h.
.SS \fBCFUNC\fR _NETCOSTINFO::costfunction[2]
.PP
Definition at line 98 of file genpart.h.
.SS int _NETCOSTINFO::ncells
.PP
Definition at line 96 of file genpart.h.
.SS int _NETCOSTINFO::numparts
.PP
Definition at line 97 of file genpart.h.
.SS int _NETCOSTINFO::row
.PP
Definition at line 97 of file genpart.h.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for madonna from the source code.