.TH _PARTLIST 3 "28 Sep 2000" "madonna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_PARTLIST \- 
.SH SYNOPSIS
.br
.PP
\fC#include <genpart.h>\fR
.PP
.SS Public Attributes

.in +1c
.ti -1c
.RI "\fBPARTCELLPTR\fR \fBcell\fR"
.br
.ti -1c
.RI "int \fBgain\fR"
.br
.ti -1c
.RI "int \fBismember\fR"
.br
.ti -1c
.RI "struct \fB_PARTITION\fR* \fBpartition\fR"
.br
.ti -1c
.RI "struct _PARTLIST* \fBnextincell\fR"
.br
.ti -1c
.RI "struct _PARTLIST* \fBnextinpart\fR"
.br
.ti -1c
.RI "struct _PARTLIST * \fBprevinpart\fR"
.br
.in -1c
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS \fBPARTCELLPTR\fR _PARTLIST::cell
.PP
Definition at line 31 of file genpart.h.
.SS int _PARTLIST::gain
.PP
Definition at line 32 of file genpart.h.
.SS int _PARTLIST::ismember
.PP
Definition at line 33 of file genpart.h.
.SS struct _PARTLIST * _PARTLIST::nextincell
.PP
Definition at line 35 of file genpart.h.
.SS struct _PARTLIST * _PARTLIST::nextinpart
.PP
Definition at line 36 of file genpart.h.
.SS struct \fB_PARTITION\fR * _PARTLIST::partition
.PP
Definition at line 34 of file genpart.h.
.SS struct _PARTLIST * _PARTLIST::previnpart
.PP
Definition at line 36 of file genpart.h.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for madonna from the source code.