.TH _PARTITION 3 "28 Sep 2000" "madonna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_PARTITION \- 
.SH SYNOPSIS
.br
.PP
\fC#include <genpart.h>\fR
.PP
.SS Public Attributes

.in +1c
.ti -1c
.RI "int \fBnumid\fR"
.br
.ti -1c
.RI "\fBPARTLISTPTR\fR \fBmembers\fR"
.br
.ti -1c
.RI "\fBPARTLISTPTR\fR \fBcandidates\fR"
.br
.ti -1c
.RI "int \fBwidth\fR"
.br
.ti -1c
.RI "int \fBheight\fR"
.br
.ti -1c
.RI "int \fBnmembers\fR"
.br
.ti -1c
.RI "int \fBcellarea\fR"
.br
.ti -1c
.RI "int \fBtargetarea\fR"
.br
.ti -1c
.RI "int \fBpermitarea\fR"
.br
.ti -1c
.RI "int \fBflag\fR"
.br
.ti -1c
.RI "struct _PARTITION* \fBnext\fR"
.br
.ti -1c
.RI "struct _PARTITION * \fBprev\fR"
.br
.in -1c
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS \fBPARTLISTPTR\fR _PARTITION::candidates
.PP
Definition at line 46 of file genpart.h.
.SS int _PARTITION::cellarea
.PP
Definition at line 49 of file genpart.h.
.SS int _PARTITION::flag
.PP
Definition at line 52 of file genpart.h.
.SS int _PARTITION::height
.PP
Definition at line 47 of file genpart.h.
.SS \fBPARTLISTPTR\fR _PARTITION::members
.PP
Definition at line 45 of file genpart.h.
.SS struct _PARTITION * _PARTITION::next
.PP
Definition at line 53 of file genpart.h.
.SS int _PARTITION::nmembers
.PP
Definition at line 48 of file genpart.h.
.SS int _PARTITION::numid
.PP
Definition at line 44 of file genpart.h.
.SS int _PARTITION::permitarea
.PP
Definition at line 51 of file genpart.h.
.SS struct _PARTITION * _PARTITION::prev
.PP
Definition at line 53 of file genpart.h.
.SS int _PARTITION::targetarea
.PP
Definition at line 50 of file genpart.h.
.SS int _PARTITION::width
.PP
Definition at line 47 of file genpart.h.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for madonna from the source code.