.TH _PARTCELL 3 "28 Sep 2000" "madonna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_PARTCELL \- 
.SH SYNOPSIS
.br
.PP
\fC#include <genpart.h>\fR
.PP
.SS Public Attributes

.in +1c
.ti -1c
.RI "CIRINSTPTR \fBcinst\fR"
.br
.ti -1c
.RI "CIRINSTPTR \fBcopycinst\fR"
.br
.ti -1c
.RI "int \fBarea\fR"
.br
.ti -1c
.RI "struct \fB_PARTLIST\fR* \fBpartlist\fR"
.br
.ti -1c
.RI "struct \fB_PNET\fR* \fBtopnets\fR"
.br
.ti -1c
.RI "struct \fB_PARTITION\fR* \fBpartition\fR"
.br
.ti -1c
.RI "int \fBflag\fR"
.br
.ti -1c
.RI "struct _PARTCELL* \fBnext\fR"
.br
.ti -1c
.RI "struct _PARTCELL * \fBprev\fR"
.br
.in -1c
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS int _PARTCELL::area
.PP
Definition at line 19 of file genpart.h.
.SS CIRINSTPTR _PARTCELL::cinst
.PP
Definition at line 17 of file genpart.h.
.SS CIRINSTPTR _PARTCELL::copycinst
.PP
Definition at line 18 of file genpart.h.
.SS int _PARTCELL::flag
.PP
Definition at line 23 of file genpart.h.
.SS struct _PARTCELL * _PARTCELL::next
.PP
Definition at line 24 of file genpart.h.
.SS struct \fB_PARTITION\fR * _PARTCELL::partition
.PP
Definition at line 22 of file genpart.h.
.SS struct \fB_PARTLIST\fR * _PARTCELL::partlist
.PP
Definition at line 20 of file genpart.h.
.SS struct _PARTCELL * _PARTCELL::prev
.PP
Definition at line 24 of file genpart.h.
.SS struct \fB_PNET\fR * _PARTCELL::topnets
.PP
Definition at line 21 of file genpart.h.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for madonna from the source code.