.TH _PIVOT 3 "28 Sep 2000" "madonna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_PIVOT \- 
.SH SYNOPSIS
.br
.PP
\fC#include <plaza.h>\fR
.PP
.SS Public Attributes

.in +1c
.ti -1c
.RI "int \fBx\fR"
.br
.ti -1c
.RI "int \fBy\fR"
.br
.ti -1c
.RI "int \fBlx\fR"
.br
.ti -1c
.RI "int \fBly\fR"
.br
.ti -1c
.RI "int \fBwx\fR"
.br
.ti -1c
.RI "int \fBwy\fR"
.br
.ti -1c
.RI "int \fBwlx\fR"
.br
.ti -1c
.RI "int \fBwly\fR"
.br
.ti -1c
.RI "short \fBwbbx\fR [2]"
.br
.ti -1c
.RI "int \fBnumsectors\fR"
.br
.ti -1c
.RI "int** \fBplaza\fR"
.br
.ti -1c
.RI "\fBPLAZGLAFPTR\fR \fBchildren\fR"
.br
.ti -1c
.RI "int \fBmaxmore\fR"
.br
.ti -1c
.RI "LAYOUTPTR \fBfather\fR"
.br
.ti -1c
.RI "\fBIMAGEDESCPTR\fR \fBimagedesc\fR"
.br
.in -1c
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS \fBPLAZGLAFPTR\fR _PIVOT::children
.PP
Definition at line 39 of file plaza.h.
.SS LAYOUTPTR _PIVOT::father
.PP
Definition at line 41 of file plaza.h.
.SS \fBIMAGEDESCPTR\fR _PIVOT::imagedesc
.PP
Definition at line 42 of file plaza.h.
.SS int _PIVOT::lx
.PP
Definition at line 34 of file plaza.h.
.SS int _PIVOT::ly
.PP
Definition at line 34 of file plaza.h.
.SS int _PIVOT::maxmore
.PP
Definition at line 40 of file plaza.h.
.SS int _PIVOT::numsectors
.PP
Definition at line 37 of file plaza.h.
.SS int ** _PIVOT::plaza
.PP
Definition at line 38 of file plaza.h.
.SS short _PIVOT::wbbx[2]
.PP
Definition at line 36 of file plaza.h.
.SS int _PIVOT::wlx
.PP
Definition at line 35 of file plaza.h.
.SS int _PIVOT::wly
.PP
Definition at line 35 of file plaza.h.
.SS int _PIVOT::wx
.PP
Definition at line 35 of file plaza.h.
.SS int _PIVOT::wy
.PP
Definition at line 35 of file plaza.h.
.SS int _PIVOT::x
.PP
Definition at line 33 of file plaza.h.
.SS int _PIVOT::y
.PP
Definition at line 33 of file plaza.h.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for madonna from the source code.