.TH _PLAZGLAF 3 "28 Sep 2000" "madonna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_PLAZGLAF \- 
.SH SYNOPSIS
.br
.PP
\fC#include <plaza.h>\fR
.PP
.SS Public Attributes

.in +1c
.ti -1c
.RI "\fBMIRPTR\fR \fBmlist\fR"
.br
.ti -1c
.RI "int \fBmore\fR"
.br
.ti -1c
.RI "LAYOUTPTR \fBlayout\fR"
.br
.ti -1c
.RI "LAYINSTPTR \fBlayinst\fR"
.br
.ti -1c
.RI "FLAG \fBflag\fR"
.br
.ti -1c
.RI "struct _PLAZGLAF* \fBnext\fR"
.br
.in -1c
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS FLAG _PLAZGLAF::flag
.PP
Definition at line 25 of file plaza.h.
.SS LAYINSTPTR _PLAZGLAF::layinst
.PP
Definition at line 24 of file plaza.h.
.SS LAYOUTPTR _PLAZGLAF::layout
.PP
Definition at line 23 of file plaza.h.
.SS \fBMIRPTR\fR _PLAZGLAF::mlist
.PP
Definition at line 21 of file plaza.h.
.SS int _PLAZGLAF::more
.PP
Definition at line 22 of file plaza.h.
.SS struct _PLAZGLAF * _PLAZGLAF::next
.PP
Definition at line 26 of file plaza.h.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for madonna from the source code.