.TH _PNET 3 "28 Sep 2000" "madonna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_PNET \- 
.SH SYNOPSIS
.br
.PP
\fC#include <genpart.h>\fR
.PP
.SS Public Attributes

.in +1c
.ti -1c
.RI "NETPTR \fBnet\fR"
.br
.ti -1c
.RI "struct _PNET* \fBnext\fR"
.br
.ti -1c
.RI "int \fBignore\fR"
.br
.in -1c
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS int _PNET::ignore
.PP
Definition at line 62 of file genpart.h.
.SS NETPTR _PNET::net
.PP
Definition at line 60 of file genpart.h.
.SS struct _PNET * _PNET::next
.PP
Definition at line 61 of file genpart.h.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for madonna from the source code.