.TH _POWERLINE 3 "28 Sep 2000" "madonna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_POWERLINE \- 
.SH SYNOPSIS
.br
.PP
\fC#include <image.h>\fR
.PP
.SS Public Attributes

.in +1c
.ti -1c
.RI "int \fBorient\fR"
.br
.ti -1c
.RI "int \fBrow_or_column\fR"
.br
.ti -1c
.RI "char* \fBname\fR"
.br
.ti -1c
.RI "int \fBlayer\fR"
.br
.ti -1c
.RI "struct _POWERLINE* \fBnext\fR"
.br
.in -1c
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS int _POWERLINE::layer
.PP
Definition at line 49 of file image.h.
.SS char * _POWERLINE::name
.PP
Definition at line 48 of file image.h.
.SS struct _POWERLINE * _POWERLINE::next
.PP
Definition at line 50 of file image.h.
.SS int _POWERLINE::orient
.PP
Definition at line 46 of file image.h.
.SS int _POWERLINE::row_or_column
.PP
Definition at line 47 of file image.h.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for madonna from the source code.