.TH _ROUTING_CHANNEL 3 "28 Sep 2000" "madonna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_ROUTING_CHANNEL \- 
.SH SYNOPSIS
.br
.PP
\fC#include <routing.h>\fR
.PP
.SS Public Attributes

.in +1c
.ti -1c
.RI "int \fBlength\fR"
.br
.ti -1c
.RI "int \fBncells\fR"
.br
.ti -1c
.RI "int \fBnwires\fR"
.br
.in -1c
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS int _ROUTING_CHANNEL::length
.PP
Definition at line 14 of file routing.h.
.SS int _ROUTING_CHANNEL::ncells
.PP
Definition at line 15 of file routing.h.
.SS int _ROUTING_CHANNEL::nwires
.PP
Definition at line 16 of file routing.h.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for madonna from the source code.