.TH _SECTORLIST 3 "28 Sep 2000" "madonna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_SECTORLIST \- 
.SH SYNOPSIS
.br
.PP
\fC#include <image.h>\fR
.PP
.SS Public Attributes

.in +1c
.ti -1c
.RI "int \fBpoint\fR [2]"
.br
.ti -1c
.RI "int \fBsectorid\fR"
.br
.ti -1c
.RI "struct _SECTORLIST* \fBnext\fR"
.br
.in -1c
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS struct _SECTORLIST * _SECTORLIST::next
.PP
Definition at line 39 of file image.h.
.SS int _SECTORLIST::point[2]
.PP
Definition at line 37 of file image.h.
.SS int _SECTORLIST::sectorid
.PP
Definition at line 38 of file image.h.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for madonna from the source code.