.TH _TOTALP 3 "28 Sep 2000" "madonna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_TOTALP \- 
.SH SYNOPSIS
.br
.PP
\fC#include <genpart.h>\fR
.PP
.SS Public Attributes

.in +1c
.ti -1c
.RI "int \fBnumparts\fR"
.br
.ti -1c
.RI "int \fBnx\fR"
.br
.ti -1c
.RI "int \fBny\fR"
.br
.ti -1c
.RI "int \fBnumcells\fR"
.br
.ti -1c
.RI "CIRCUITPTR \fBtopcell\fR"
.br
.ti -1c
.RI "\fBGLOBAL_ROUTINGPTR\fR \fBrouting\fR"
.br
.ti -1c
.RI "CIRCUITPTR \fBbestpart\fR"
.br
.ti -1c
.RI "int \fBbestnetcost\fR"
.br
.ti -1c
.RI "int \fBbestmove\fR"
.br
.ti -1c
.RI "int \fBstrtnetcost\fR"
.br
.ti -1c
.RI "\fBCFUNC\fR* \fBcostfunction\fR"
.br
.ti -1c
.RI "int* \fBtmpstatebuf\fR"
.br
.ti -1c
.RI "\fBPARTITIONPTR\fR \fBpartition\fR"
.br
.ti -1c
.RI "\fBPARTCELLPTR\fR \fBpartcell\fR"
.br
.ti -1c
.RI "int \fBarea\fR"
.br
.ti -1c
.RI "int \fBnetcost\fR"
.br
.ti -1c
.RI "int \fBnmoves\fR"
.br
.ti -1c
.RI "int \fBrepeat\fR"
.br
.ti -1c
.RI "int \fBstopcriterion\fR"
.br
.ti -1c
.RI "double \fBtemperature\fR"
.br
.ti -1c
.RI "double \fBcooling\fR"
.br
.in -1c
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS int _TOTALP::area
.PP
Definition at line 83 of file genpart.h.
.SS int _TOTALP::bestmove
.PP
Definition at line 76 of file genpart.h.
.SS int _TOTALP::bestnetcost
.PP
Definition at line 75 of file genpart.h.
.SS CIRCUITPTR _TOTALP::bestpart
.PP
Definition at line 74 of file genpart.h.
.SS double _TOTALP::cooling
.PP
Definition at line 89 of file genpart.h.
.SS \fBCFUNC\fR * _TOTALP::costfunction
.PP
Definition at line 78 of file genpart.h.
.SS int _TOTALP::netcost
.PP
Definition at line 84 of file genpart.h.
.SS int _TOTALP::nmoves
.PP
Definition at line 85 of file genpart.h.
.SS int _TOTALP::numcells
.PP
Definition at line 71 of file genpart.h.
.SS int _TOTALP::numparts
.PP
Definition at line 69 of file genpart.h.
.SS int _TOTALP::nx
.PP
Definition at line 70 of file genpart.h.
.SS int _TOTALP::ny
.PP
Definition at line 70 of file genpart.h.
.SS \fBPARTCELLPTR\fR _TOTALP::partcell
.PP
Definition at line 82 of file genpart.h.
.SS \fBPARTITIONPTR\fR _TOTALP::partition
.PP
Definition at line 81 of file genpart.h.
.SS int _TOTALP::repeat
.PP
Definition at line 86 of file genpart.h.
.SS \fBGLOBAL_ROUTINGPTR\fR _TOTALP::routing
.PP
Definition at line 73 of file genpart.h.
.SS int _TOTALP::stopcriterion
.PP
Definition at line 87 of file genpart.h.
.SS int _TOTALP::strtnetcost
.PP
Definition at line 77 of file genpart.h.
.SS double _TOTALP::temperature
.PP
Definition at line 88 of file genpart.h.
.SS int * _TOTALP::tmpstatebuf
.PP
Definition at line 80 of file genpart.h.
.SS CIRCUITPTR _TOTALP::topcell
.PP
Definition at line 72 of file genpart.h.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for madonna from the source code.