.TH basearr.h 3 "28 Sep 2000" "madonna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
basearr.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream.h>\fR
.br
\fC#include <basedefs.h>\fR
.br
\fC#include <item.h>\fR
.br
\fC#include <package.h>\fR
.br
.SS Compounds

.in +1c
.ti -1c
.RI "class \fBArrayIterator\fR"
.br
.ti -1c
.RI "class \fBBaseArray\fR"
.br
.in -1c
.SH AUTHOR
.PP 
Generated automatically by Doxygen for madonna from the source code.