.TH compact.C 3 "28 Sep 2000" "madonna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
compact.C \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib.h>\fR
.br
\fC#include <math.h>\fR
.br
\fC#include <string.h>\fR
.br
\fC#include "plcm.h"\fR
.br
.SH AUTHOR
.PP 
Generated automatically by Doxygen for madonna from the source code.