.TH connectInfo 3 "28 Sep 2000" "madonna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
connectInfo \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBmatrixInt\fR.
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBconnectInfo\fR (int numparts, CIRCUITPTR)"
.br
.ti -1c
.RI "int \fBoperator()\fR (int pi, int pj)"
.br
.ti -1c
.RI "int \fBnumparts\fR ()"
.br
.in -1c
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS connectInfo::connectInfo (int numparts, CIRCUITPTR circuit)
.PP
Definition at line 40 of file clusterPerm.C.
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS int connectInfo::numparts ()\fC [inline]\fR
.PP
Definition at line 18 of file clusterPerm.C.
.PP
Referenced by \fBapplyPermutation\fR(), and \fBclusterCost\fR().
.SS int connectInfo::operator() (int pi, int pj)
.PP
Definition at line 33 of file clusterPerm.C.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for madonna from the source code.