.TH cri.h 3 "28 Sep 2000" "madonna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cri.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "point.h"\fR
.br
\fC#include <list.h>\fR
.br
.SS Compounds

.in +1c
.ti -1c
.RI "class \fBCriNet\fR"
.br
.ti -1c
.RI "class \fBCriPoint\fR"
.br
.in -1c
.SH AUTHOR
.PP 
Generated automatically by Doxygen for madonna from the source code.