.TH debug.C 3 "28 Sep 2000" "madonna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
debug.C \- 
.SH SYNOPSIS
.br
.PP
\fC#include <sea_func.h>\fR
.br
\fC#include <sealib.h>\fR
.br
\fC#include "image.h"\fR
.br
\fC#include "plaza.h"\fR
.br
\fC#include "im.h"\fR
.br
.SS Functions

.in +1c
.ti -1c
.RI "void \fBprintstamp\fR (\fBIMAGEDESCPTR\fR imagedesc)"
.br
.ti -1c
.RI "void \fBprintequiv\fR (\fBIMAGEDESCPTR\fR imagedesc)"
.br
.ti -1c
.RI "void \fBprintpivot\fR (\fBPIVOTPTR\fR pivot)"
.br
.ti -1c
.RI "void \fBprintchild\fR (\fBPIVOTPTR\fR pivot)"
.br
.ti -1c
.RI "void \fBprintmtx\fR (short *mtx)"
.br
.in -1c
.SH FUNCTION DOCUMENTATION
.PP 
.SS void printchild (\fBPIVOTPTR\fR pivot)
.PP
Definition at line 54 of file debug.C.
.SS void printequiv (\fBIMAGEDESCPTR\fR imagedesc)
.PP
Definition at line 29 of file debug.C.
.SS void printmtx (short * mtx)
.PP
Definition at line 78 of file debug.C.
.SS void printpivot (\fBPIVOTPTR\fR pivot)
.PP
Definition at line 45 of file debug.C.
.SS void printstamp (\fBIMAGEDESCPTR\fR imagedesc)
.PP
Definition at line 13 of file debug.C.
.SH AUTHOR
.PP 
Generated automatically by Doxygen for madonna from the source code.