.TH expansionGridTerminal 3 "28 Sep 2000" "madonna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
expansionGridTerminal \- 
.SH SYNOPSIS
.br
.PP
\fC#include <globRoute.h>\fR
.PP
Inherits \fBgraphTerminal\fR.
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBexpansionGridTerminal\fR (\fBpointOfCompass\fR cmpss)"
.br
.ti -1c
.RI "\fBpointOfCompass\fR \fBcompass\fR ()"
.br
.in -1c
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS expansionGridTerminal::expansionGridTerminal (\fBpointOfCompass\fR cmpss)\fC [inline]\fR
.PP
Definition at line 37 of file globRoute.h.
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS \fBpointOfCompass\fR expansionGridTerminal::compass ()\fC [inline]\fR
.PP
Definition at line 38 of file globRoute.h.
.PP
Referenced by \fBexpansionGrid::findEdge\fR().

.SH AUTHOR
.PP 
Generated automatically by Doxygen for madonna from the source code.