.TH globTerm 3 "28 Sep 2000" "madonna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
globTerm \- 
.SH SYNOPSIS
.br
.PP
\fC#include <globRoute.h>\fR
.PP
Inherits \fBtreeVertex\fR.
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBglobTerm\fR (\fBexpansionGridVertex\fR *egv)"
.br
.ti -1c
.RI "\fBexpansionGridVertex\fR* \fBgridVx\fR ()"
.br
.in -1c
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS globTerm::globTerm (\fBexpansionGridVertex\fR * egv)
.PP
Definition at line 105 of file globRoute.h.
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS \fBexpansionGridVertex\fR * globTerm::gridVx ()\fC [inline]\fR
.PP
Definition at line 106 of file globRoute.h.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for madonna from the source code.