.TH globRoute.h 3 "28 Sep 2000" "madonna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
globRoute.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <sealib.h>\fR
.br
\fC#include <sdfset.h>\fR
.br
\fC#include <graph.h>\fR
.br
\fC#include <graphSteiner.h>\fR
.br
\fC#include "genpart.h"\fR
.br
\fC#include "matrixGrid.h"\fR
.br
\fC#include "image.h"\fR
.br
.SS Compounds

.in +1c
.ti -1c
.RI "class \fBexpansionGrid\fR"
.br
.ti -1c
.RI "class \fBexpansionGridEdge\fR"
.br
.ti -1c
.RI "class \fBexpansionGridTerminal\fR"
.br
.ti -1c
.RI "class \fBexpansionGridVertex\fR"
.br
.ti -1c
.RI "class \fBglobNet\fR"
.br
.ti -1c
.RI "class \fBglobTerm\fR"
.br
.in -1c
.SS Enumerations

.in +1c
.ti -1c
.RI "enum \fBpointOfCompass\fR { \fBNowhere\fR, \fBSouth\fR, \fBEast\fR, \fBNorth\fR, \fBWest\fR }"
.br
.ti -1c
.RI "enum \fBedgeDirection\fR { \fBHorizontalEdge\fR, \fBVerticalEdge\fR }"
.br
.ti -1c
.RI "enum \fBexpansionGridVertexType\fR { \fBPartitionGV\fR, \fBHorizontalChannelGV\fR, \fBVerticalChannelGV\fR, \fBChannelCrossingGV\fR }"
.br
.in -1c
.SH ENUMERATION TYPE DOCUMENTATION
.PP 
.SS enum edgeDirection
.PP
\fBEnumeration values:\fR
.in +1c
.TP
\fB\fIHorizontalEdge\fR \fR
.TP
\fB\fIVerticalEdge\fR \fR
.PP
Definition at line 24 of file globRoute.h.
.SS enum expansionGridVertexType
.PP
\fBEnumeration values:\fR
.in +1c
.TP
\fB\fIPartitionGV\fR \fR
.TP
\fB\fIHorizontalChannelGV\fR \fR
.TP
\fB\fIVerticalChannelGV\fR \fR
.TP
\fB\fIChannelCrossingGV\fR \fR
.PP
Definition at line 25 of file globRoute.h.
.SS enum pointOfCompass
.PP
\fBEnumeration values:\fR
.in +1c
.TP
\fB\fINowhere\fR \fR
.TP
\fB\fISouth\fR \fR
.TP
\fB\fIEast\fR \fR
.TP
\fB\fINorth\fR \fR
.TP
\fB\fIWest\fR \fR
.PP
Definition at line 23 of file globRoute.h.
.SH AUTHOR
.PP 
Generated automatically by Doxygen for madonna from the source code.