.TH layoutMapType 3 "28 Sep 2000" "madonna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
layoutMapType \- 
.SH SYNOPSIS
.br
.PP
\fC#include <phil.h>\fR
.PP
.SS Public Attributes

.in +1c
.ti -1c
.RI "unsigned char \fBlayers\fR"
.br
.ti -1c
.RI "unsigned char \fBvisited\fR"
.br
.ti -1c
.RI "unsigned char \fBuniNo\fR"
.br
.ti -1c
.RI "unsigned int \fBtermNo\fR"
.br
.ti -1c
.RI "unsigned char \fBupWay\fR"
.br
.ti -1c
.RI "unsigned char \fBdownWay\fR"
.br
.ti -1c
.RI "unsigned char \fBleftWay\fR"
.br
.ti -1c
.RI "unsigned char \fBrightWay\fR"
.br
.in -1c
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS unsigned char layoutMapType::downWay
.PP
Definition at line 71 of file phil.h.
.SS unsigned char layoutMapType::layers
.PP
Definition at line 65 of file phil.h.
.SS unsigned char layoutMapType::leftWay
.PP
Definition at line 72 of file phil.h.
.SS unsigned char layoutMapType::rightWay
.PP
Definition at line 73 of file phil.h.
.SS unsigned int layoutMapType::termNo
.PP
Definition at line 68 of file phil.h.
.SS unsigned char layoutMapType::uniNo
.PP
Definition at line 67 of file phil.h.
.SS unsigned char layoutMapType::upWay
.PP
Definition at line 70 of file phil.h.
.SS unsigned char layoutMapType::visited
.PP
Definition at line 66 of file phil.h.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for madonna from the source code.