.TH ListElement 3 "28 Sep 2000" "madonna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ListElement \- 
.SH SYNOPSIS
.br
.PP
\fC#include <lstelem.h>\fR
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBListElement\fR ( \fBItem\fR *i )"
.br
.ti -1c
.RI "\fB~ListElement\fR ()"
.br
.in -1c
.SS Friends

.in +1c
.ti -1c
.RI "class \fBList\fR"
.br
.ti -1c
.RI "class \fBListIterator\fR"
.br
.in -1c
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS ListElement::ListElement (\fBItem\fR * i)\fC [inline]\fR
.PP
Definition at line 29 of file lstelem.h.
.SS ListElement::~ListElement ()\fC [inline]\fR
.PP
Definition at line 30 of file lstelem.h.
.SH FRIENDS AND RELATED FUNCTION DOCUMENTATION
.PP 
.SS class List\fC [friend]\fR
.PP
Definition at line 35 of file lstelem.h.
.SS class ListIterator\fC [friend]\fR
.PP
Definition at line 36 of file lstelem.h.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for madonna from the source code.