.TH lstelem.h 3 "28 Sep 2000" "madonna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lstelem.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream.h>\fR
.br
\fC#include "basedefs.h"\fR
.br
\fC#include "item.h"\fR
.br
.SS Compounds

.in +1c
.ti -1c
.RI "class \fBListElement\fR"
.br
.in -1c
.SH AUTHOR
.PP 
Generated automatically by Doxygen for madonna from the source code.