.TH myfree.C 3 "28 Sep 2000" "madonna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
myfree.C \- 
.SH SYNOPSIS
.br
.PP
\fC#include <malloc.h>\fR
.br
.SS Functions

.in +1c
.ti -1c
.RI "void \fBmyfree\fR (void *ptr)"
.br
.in -1c
.SH FUNCTION DOCUMENTATION
.PP 
.SS void myfree (void * ptr)
.PP
Definition at line 5 of file myfree.C.
.SH AUTHOR
.PP 
Generated automatically by Doxygen for madonna from the source code.