.TH parserIf.h 3 "28 Sep 2000" "madonna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
parserIf.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "phil.h"\fR
.br
\fC#include "imageMap.h"\fR
.br
.SS Compounds

.in +1c
.ti -1c
.RI "class \fBParserInterface\fR"
.br
.in -1c
.SH AUTHOR
.PP 
Generated automatically by Doxygen for madonna from the source code.