.TH PlaneCell 3 "28 Sep 2000" "madonna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlaneCell \- 
.SH SYNOPSIS
.br
.PP
\fC#include <plane.h>\fR
.PP
Inherits \fBList\fR.
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBPlaneCell\fR ()"
.br
.ti -1c
.RI "\fB~PlaneCell\fR ()"
.br
.ti -1c
.RI "virtual \fBclassType\fR \fBmyNo\fR () const"
.br
.ti -1c
.RI "virtual char* \fBmyName\fR () const"
.br
.in -1c
.SS Public Attributes

.in +1c
.ti -1c
.RI "\fBclusterMapType\fR \fBpattern\fR"
.br
.in -1c
.SH CONSTRUCTOR & DESTRUCTOR DOCUMENTATION
.PP 
.SS PlaneCell::PlaneCell ()
.PP
Definition at line 17 of file plane.h.
.SS PlaneCell::~PlaneCell ()\fC [inline]\fR
.PP
Definition at line 19 of file plane.h.
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS char * PlaneCell::myName () const\fC [inline, virtual]\fR
.PP
Reimplemented from \fBList\fR.
.PP
Definition at line 22 of file plane.h.
.SS \fBclassType\fR PlaneCell::myNo () const\fC [inline, virtual]\fR
.PP
Reimplemented from \fBList\fR.
.PP
Definition at line 21 of file plane.h.
.SH MEMBER DATA DOCUMENTATION
.PP 
.SS \fBclusterMapType\fR PlaneCell::pattern
.PP
Definition at line 25 of file plane.h.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for madonna from the source code.