.TH routing.h 3 "28 Sep 2000" "madonna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
routing.h \- 
.SH SYNOPSIS
.br
.PP
.SS Compounds

.in +1c
.ti -1c
.RI "struct \fB_GLOBAL_ROUTING\fR"
.br
.ti -1c
.RI "struct \fB_ROUTING_CHANNEL\fR"
.br
.ti -1c
.RI "struct \fB_ROUTING_INFO\fR"
.br
.in -1c
.SS Typedefs

.in +1c
.ti -1c
.RI "typedef struct \fB_ROUTING_CHANNEL\fR
 \fBROUTING_CHANNEL\fR"
.br
.ti -1c
.RI "typedef struct \fB_ROUTING_CHANNEL\fR * \fBROUTING_CHANNELPTR\fR"
.br
.ti -1c
.RI "typedef struct \fB_ROUTING_INFO\fR
 \fBROUTING_INFO\fR"
.br
.ti -1c
.RI "typedef struct \fB_ROUTING_INFO\fR * \fBROUTING_INFOPTR\fR"
.br
.ti -1c
.RI "typedef struct \fB_GLOBAL_ROUTING\fR
 \fBGLOBAL_ROUTING\fR"
.br
.ti -1c
.RI "typedef struct \fB_GLOBAL_ROUTING\fR * \fBGLOBAL_ROUTINGPTR\fR"
.br
.in -1c
.SH TYPEDEF DOCUMENTATION
.PP 
.SS typedef struct \fB_GLOBAL_ROUTING\fR
 GLOBAL_ROUTING
.PP
.SS typedef struct \fB_GLOBAL_ROUTING\fR * GLOBAL_ROUTINGPTR
.PP
.SS typedef struct \fB_ROUTING_CHANNEL\fR
 ROUTING_CHANNEL
.PP
.SS typedef struct \fB_ROUTING_CHANNEL\fR * ROUTING_CHANNELPTR
.PP
.SS typedef struct \fB_ROUTING_INFO\fR
 ROUTING_INFO
.PP
.SS typedef struct \fB_ROUTING_INFO\fR * ROUTING_INFOPTR
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for madonna from the source code.