.TH sea.h 3 "28 Sep 2000" "madonna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sea.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include "image.h"\fR
.br
\fC#include <sea_func.h>\fR
.br
\fC#include <sealib.h>\fR
.br
\fC#include "im.h"\fR
.br
.SS Defines

.in +1c
.ti -1c
.RI "#define \fBNULL\fR  0"
.br
.in -1c
.SS Enumerations

.in +1c
.ti -1c
.RI "enum \fBBoolean\fR { \fBfalse\fR = int(0), \fBtrue\fR = int(1) }"
.br
.in -1c
.SH DEFINE DOCUMENTATION
.PP 
.SS #define NULL  0
.PP
Definition at line 15 of file sea.h.
.SH ENUMERATION TYPE DOCUMENTATION
.PP 
.SS enum Boolean
.PP
\fBEnumeration values:\fR
.in +1c
.TP
\fB\fIfalse\fR \fR
.TP
\fB\fItrue\fR \fR
.PP
Definition at line 24 of file sea.h.
.PP
Referenced by \fBPlcm::createPlane\fR(), and \fBphil\fR().
.SH AUTHOR
.PP 
Generated automatically by Doxygen for madonna from the source code.