.TH stuff.C 3 "28 Sep 2000" "madonna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stuff.C \- 
.SH SYNOPSIS
.br
.PP
\fC#include <malloc.h>\fR
.br
\fC#include "sea.h"\fR
.br
.SS Defines

.in +1c
.ti -1c
.RI "#define \fBALIGNMOD\fR  8"
.br
.ti -1c
.RI "#define \fBALIGNBITS\fR  (ALIGNMOD-1)"
.br
.in -1c
.SS Functions

.in +1c
.ti -1c
.RI "char* \fBballoc\fR (int size)"
.br
.ti -1c
.RI "void \fBbfree\fR (char *blk)"
.br
.in -1c
.SH DEFINE DOCUMENTATION
.PP 
.SS #define ALIGNBITS  (ALIGNMOD-1)
.PP
Definition at line 10 of file stuff.C.
.SS #define ALIGNMOD  8
.PP
Definition at line 9 of file stuff.C.
.SH FUNCTION DOCUMENTATION
.PP 
.SS char * balloc (int size)
.PP
Definition at line 14 of file stuff.C.
.PP
Referenced by \fBinitimagedesc\fR().
.SS void bfree (char * blk)
.PP
Definition at line 20 of file stuff.C.
.SH AUTHOR
.PP 
Generated automatically by Doxygen for madonna from the source code.