.TH thedate.C 3 "28 Sep 2000" "madonna" \" -*- nroff -*-
.ad l
.nh
.SH NAME
thedate.C \- 
.SH SYNOPSIS
.br
.PP
.SS Defines

.in +1c
.ti -1c
.RI "#define \fBTHEDATE\fR  "<compile date not available>""
.br
.ti -1c
.RI "#define \fBTHEHOST\fR  "<hostname not available>""
.br
.ti -1c
.RI "#define \fBTHEMAN\fR  "Mickey Mouse""
.br
.in -1c
.SS Variables

.in +1c
.ti -1c
.RI "char* \fBthedate\fR = THEDATE"
.br
.ti -1c
.RI "char* \fBthehost\fR = THEHOST"
.br
.ti -1c
.RI "char* \fBtheman\fR = THEMAN"
.br
.ti -1c
.RI "char* \fBmadonna_version\fR = "3.2""
.br
.in -1c
.SH DEFINE DOCUMENTATION
.PP 
.SS #define THEDATE  "<compile date not available>"
.PP
Definition at line 6 of file thedate.C.
.SS #define THEHOST  "<hostname not available>"
.PP
Definition at line 10 of file thedate.C.
.SS #define THEMAN  "Mickey Mouse"
.PP
Definition at line 14 of file thedate.C.
.SH VARIABLE DOCUMENTATION
.PP 
.SS char * madonna_version = "3.2"
.PP
Definition at line 21 of file thedate.C.
.SS char * thedate = THEDATE
.PP
Definition at line 18 of file thedate.C.
.SS char * thehost = THEHOST
.PP
Definition at line 19 of file thedate.C.
.SS char * theman = THEMAN
.PP
Definition at line 20 of file thedate.C.
.SH AUTHOR
.PP 
Generated automatically by Doxygen for madonna from the source code.